apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cofrap-front
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: ui.cofrap.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: cofrap-front
                port:
                  number: 80
